services:
  - type: web
    name: remixyumusbot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "8609012191"
      - key: ADMIN_USERNAME
        value: "vvpse"
      - key: DB_PATH
        value: "/app/storage/remix.db"
